DRIVER - Debug mode enabled
SUB140061166554320<A,B,C> - - Initializing subscriber to centralized broker
SUB140061166554320<A,B,C> - - Try to connect with ZooKeeper server: hosts = 10.0.0.1:2181
SUB140061166554320<A,B,C> - - ZooKeeper Current Status = LOST
Connection dropped: socket connection error: No route to host
Connection dropped: socket connection error: No route to host
Connection dropped: socket connection error: None
Failed connecting to Zookeeper within the connection retry policy.
SUB140061166554320<A,B,C> - - Exception thrown in start (): <class 'kazoo.handlers.threading.KazooTimeoutError'>
SUB140061166554320<A,B,C> - - Checking if /broker exists (it should)
SUB140061166554320<A,B,C> - - Exception thrown checking for exists/get: <class 'kazoo.exceptions.ConnectionClosedError'>
SUB140061166554320<A,B,C> - - Subscribe Start
SUB140061166554320<A,B,C> - - Start to receive message
Traceback (most recent call last):
  File "driver.py", line 278, in <module>
    subscribers = create_subscribers(
  File "driver.py", line 96, in create_subscribers
    create_subscriber_with_zookeeper(subs[i])
  File "driver.py", line 65, in create_subscriber_with_zookeeper
    subscriber.notify()
  File "/mnt/dev/assign2/src/lib/subscriber.py", line 301, in notify
    events = dict(self.poller.poll())
AttributeError: 'NoneType' object has no attribute 'poll'
